// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: auth.sql

package db

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const getRefreshTokenByHash = `-- name: GetRefreshTokenByHash :one
SELECT id, usuario_id, org_id, token_hash, expira_at, revocado, created_at
FROM refresh_tokens
WHERE token_hash = $1
LIMIT 1
`

func (q *Queries) GetRefreshTokenByHash(ctx context.Context, tokenHash string) (RefreshToken, error) {
	row := q.db.QueryRowContext(ctx, getRefreshTokenByHash, tokenHash)
	var i RefreshToken
	err := row.Scan(
		&i.ID,
		&i.UsuarioID,
		&i.OrgID,
		&i.TokenHash,
		&i.ExpiraAt,
		&i.Revocado,
		&i.CreatedAt,
	)
	return i, err
}

const getRolesByUsuario = `-- name: GetRolesByUsuario :many
SELECT org_id, rol
FROM usuario_organizacion
WHERE usuario_id = $1
`

type GetRolesByUsuarioRow struct {
	OrgID uuid.UUID `json:"org_id"`
	Rol   RolEnum   `json:"rol"`
}

func (q *Queries) GetRolesByUsuario(ctx context.Context, usuarioID uuid.UUID) ([]GetRolesByUsuarioRow, error) {
	rows, err := q.db.QueryContext(ctx, getRolesByUsuario, usuarioID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetRolesByUsuarioRow
	for rows.Next() {
		var i GetRolesByUsuarioRow
		if err := rows.Scan(&i.OrgID, &i.Rol); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUsuarioByEmail = `-- name: GetUsuarioByEmail :one
SELECT id, email, password_hash, created_at
FROM usuarios
WHERE email = $1
LIMIT 1
`

func (q *Queries) GetUsuarioByEmail(ctx context.Context, email string) (Usuario, error) {
	row := q.db.QueryRowContext(ctx, getUsuarioByEmail, email)
	var i Usuario
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.CreatedAt,
	)
	return i, err
}

const insertRefreshToken = `-- name: InsertRefreshToken :exec
INSERT INTO refresh_tokens (usuario_id, org_id, token_hash, expira_at)
VALUES ($1, $2, $3, $4)
`

type InsertRefreshTokenParams struct {
	UsuarioID uuid.UUID `json:"usuario_id"`
	OrgID     uuid.UUID `json:"org_id"`
	TokenHash string    `json:"token_hash"`
	ExpiraAt  time.Time `json:"expira_at"`
}

func (q *Queries) InsertRefreshToken(ctx context.Context, arg InsertRefreshTokenParams) error {
	_, err := q.db.ExecContext(ctx, insertRefreshToken,
		arg.UsuarioID,
		arg.OrgID,
		arg.TokenHash,
		arg.ExpiraAt,
	)
	return err
}

const revokeAllTokensByUsuario = `-- name: RevokeAllTokensByUsuario :exec
UPDATE refresh_tokens
SET revocado = TRUE
WHERE usuario_id = $1
`

func (q *Queries) RevokeAllTokensByUsuario(ctx context.Context, usuarioID uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, revokeAllTokensByUsuario, usuarioID)
	return err
}

const revokeRefreshToken = `-- name: RevokeRefreshToken :exec
UPDATE refresh_tokens
SET revocado = TRUE
WHERE id = $1
`

func (q *Queries) RevokeRefreshToken(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, revokeRefreshToken, id)
	return err
}
