// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"database/sql/driver"
	"fmt"
	"time"

	"github.com/google/uuid"
)

type RolEnum string

const (
	RolEnumAdmin   RolEnum = "admin"
	RolEnumJudge   RolEnum = "judge"
	RolEnumBrewery RolEnum = "brewery"
)

func (e *RolEnum) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = RolEnum(s)
	case string:
		*e = RolEnum(s)
	default:
		return fmt.Errorf("unsupported scan type for RolEnum: %T", src)
	}
	return nil
}

type NullRolEnum struct {
	RolEnum RolEnum `json:"rol_enum"`
	Valid   bool    `json:"valid"` // Valid is true if RolEnum is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullRolEnum) Scan(value interface{}) error {
	if value == nil {
		ns.RolEnum, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.RolEnum.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullRolEnum) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.RolEnum), nil
}

type Organizacione struct {
	ID        uuid.UUID `json:"id"`
	Name      string    `json:"name"`
	CreatedAt time.Time `json:"created_at"`
}

type RefreshToken struct {
	ID        uuid.UUID `json:"id"`
	UsuarioID uuid.UUID `json:"usuario_id"`
	OrgID     uuid.UUID `json:"org_id"`
	TokenHash string    `json:"token_hash"`
	ExpiraAt  time.Time `json:"expira_at"`
	Revocado  bool      `json:"revocado"`
	CreatedAt time.Time `json:"created_at"`
}

type Usuario struct {
	ID           uuid.UUID `json:"id"`
	Email        string    `json:"email"`
	PasswordHash string    `json:"password_hash"`
	CreatedAt    time.Time `json:"created_at"`
}

type UsuarioOrganizacion struct {
	UsuarioID uuid.UUID `json:"usuario_id"`
	OrgID     uuid.UUID `json:"org_id"`
	Rol       RolEnum   `json:"rol"`
}
